nodes:
  amount: 0
  cpu: 1500
customNodes:
  - name: small
    cpu: 1
  - name: medium
    cpu: 2
  - name: large
    cpu: 4
scaler:
  holdTimeUpScaler: 0
  holdTimeDownScaler: 300
loadBalancer: leastUtil_orchestration
scheduler: firstFit
scalingInterval: 15
healthCheckDelay: 0
#schedulerPrio:
#  - name: kube
#    prio: 1
#  - name: firstFit
#    prio: 2
#startUpTimeContainer:
#  - name: frontend
#    time: 0
#  - name: backend
#    time: 0