nodes:
  amount: 2
  cpu: 100
customNodes:
  - name: Test5Node
    cpu: 0
scaler:
  holdTimeUpScaler: 5
  holdTimeDownScaler: 3
loadBalancer: leastUtil_orchestration
scheduler: firstFit
schedulerPrio:
  - name: kube
    prio: 4
  - name: firstFit
    prio: 3
startUpTimeContainer:
  - name: frontend
    time: 0
  - name: backend
    time: 0
  - name: db
    time: 0