nodes:
  amount: 2
  cpu: 10
customNodes:
  - name: Test5Node
    cpu: 0
scaler:
  holdTimeUpScaler: 5
  holdTimeDownScaler: 3
loadBalancer: leastUtil_orchestration
scheduler: firstFit
schedulerPrio:
  - name: kube
    prio: 4
  - name: firstFit
    prio: 3
startUpTimeContainer:
  - name: frontend
    time: 5