nodes:
  amount: 2
  cpu: 1000000000
customNodes:
  - name: Test5Node
    cpu: 0
scaler:
  holdTimeUpScaler: 0
  holdTimeDownScaler: 20
loadBalancer: leastUtil_orchestration
scheduler: firstFit
healthCheckInterval: 30
schedulerPrio:
  - name: kube
    prio: 4
  - name: firstFit
    prio: 3
startUpTimeContainer:
  - name: frontend
    time: 0
  - name: backend
    time: 0
  - name: db
    time: 0