nodes:
  amount: 1
  cpu: 10
customNodes:
  - name: Test5Node
    cpu: 5
  - name: Test6Node
    cpu: 6
  - name: Large
    cpu: 10
scaler:
  holdTimeUpScaler: 5
  holdTimeDownScaler: 3
loadBalancer: random_orchestration
scheduler: firstFit
schedulerPrio:
  - name: kube
    prio: 2
  - name: firstFit
    prio: 3
