package cambio.simulator.entities.networking;

import cambio.simulator.entities.generator.LoadGeneratorDescriptionExecutor;
import cambio.simulator.entities.microservice.Operation;
import cambio.simulator.export.ReportCollector;
import cambio.simulator.models.MiSimModel;

/**
 * A {@code Request} that represents a request that is created by a user from outside the simulated system.
 *
 * <p>
 * These type of requests are generated by the {@code Generator}s and do not have a parent request. They are usually the
 * root request of a trace.
 *
 * @author Lion Wagner
 * @see LoadGeneratorDescriptionExecutor
 */
public class UserRequest extends Request {

    public UserRequest(MiSimModel model, String name, boolean showInTrace, Operation operation) {
        super(model, name, showInTrace, null, operation, null);
    }

    @Override
    protected void onReceive() {
        super.onReceive();
        ReportCollector.USER_REQUEST_REPORTER
            .addDatapoint(String.format("[%s]_ResponseTimes", operation.getName()), presentTime(), getResponseTime());
        ReportCollector.USER_REQUEST_REPORTER
            .addDatapoint("[All]ResponseTimes", presentTime(), getResponseTime());
    }
}
