apiVersion: apps/v1
kind: Deployment
metadata:
  name: authService-deployment
  labels:
    app: authService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authService
  template:
    metadata:
      labels:
        app: authService
    spec:
      schedulerName: firstFit
      containers:
        - name: authService
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                  - key: personalized/name
#                    operator: In
#                    values:
#                      - authService
