apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptionService-deployment
  labels:
    app: subscriptionService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriptionService
  template:
    metadata:
      labels:
        app: subscriptionService
    spec:
      containers:
        - name: subscriptionService
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                  - key: personalized/name
#                    operator: In
#                    values:
#                      - Node1
