apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersService-deployment
  labels:
    app: usersService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usersService
  template:
    metadata:
      labels:
        app: usersService
    spec:
      schedulerName: firstFit
      containers:
        - name: usersService
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                  - key: personalized/name
#                    operator: In
#                    values:
#                      - usersService
