apiVersion: apps/v1
kind: Deployment
metadata:
  name: videoPlayerService-deployment
  labels:
    app: videoPlayerService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: videoPlayerService
  template:
    metadata:
      labels:
        app: videoPlayerService
    spec:
      containers:
        - name: videoPlayerService
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                  - key: personalized/name
#                    operator: In
#                    values:
#                      - Node1
