name: Check Links
on: [push, pull_request]

jobs: 
  check_links: 
    name: Check Links
    runs-on: ubuntu-latest
    steps:
     - name: Setup Ruby
       uses: ruby/setup-ruby@v1
     - name: Install awesome bot
       run:  gem install awesome_bot
     - name: Run Awesome_Bot
       run: awesome_bot README.md --allow-dupe --allow-redirect
        
