name: Publish Artifact

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build_artifact:  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Java 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file pom.xml "-DskipTests=true" "-Dmaven.javadoc.skip=true" "-Dcheckstyle.skipExec=true"
          
    - name: Copy Data
      run: mkdir staging && cp target/*.jar staging
      
    - name: upload artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: miSim 3.0
        path: ./staging/
              
  run_tests:  
    runs-on: ubuntu-latest
    steps:
    - name: Set up Java 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: 'maven'        
    
    - name: Run JUnit Tests
      run: mvn -B test --file pom.xml "-Dcheckstyle.skipExec=true"
  
  run_hello_world:    
    runs-on: ubuntu-latest
    steps:
    - name: Set up Java 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: 'maven'
    - name: Run Hello World
      run: ./runHelloWorld.sh
