# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publish Artifact

on:
  push:
    branches: [ master, Version3 ]
  workflow_dispatch:
    
jobs:
  build_artifact:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: register desmoj to maven 
      run: mvn install:install-file -Dfile=./libraries/DesmoJ/desmoj-2.5.1e-bin.jar -Dversion=2.5.1e -DgeneratePom=true -DgroupId=desmoj -DartifactId=desmoj -Dpackaging=jar
    
    - name: Cache Maven Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: |
          mvn -B package --file pom.xml "-Dmaven.javadoc.skip=true" "-Dcheckstyle.skipExec=true"
          
    - name: Copy Data
      run: mkdir staging && cp target/*.jar staging
      
      
    - name: upload artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: miSim 3.0
        path: ./staging/
