name: Run Checkstyle

on:
  push:
  pull_request:
    branches: [ master ] # trigger for automatic PRs from workflow bot

jobs:
  run_checkstyle:
    name: Run Checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: 'maven'

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Create Checkstyle Report Annotations
        uses: jwgmeligmeyling/checkstyle-github-action@master
        # if: (success() || failure()) && (github.event.pull_request == '' || github.event.pull_request.head.repo.fork == false)
        with:
          name: Checkstyle Report
          path: ./target/checkstyle-result.xml

      - name: Upload Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-result
          path: ./target/checkstyle-result.xml

