name: Run Checkstyle

on:
  push:
  pull_request:

jobs:
  run_checkstyle:
    if: "!contains(github.event.head_commit.message, '[maven-release-plugin]')"
    name: Run Checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Run Checkstyle
        run: mvn checkstyle:check
        env:
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES }}

      - name: Create Checkstyle Report Annotations
        uses: cmelchior/checkstyle-github-action@master
        if: (success() || failure()) && (github.event.pull_request == '' || github.event.pull_request.head.repo.fork == false)
        with:
          name: Checkstyle Report
          path: ./target/checkstyle-result.xml
