# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Run Checkstyle

on:
  pull_request:
    branches: [master, Version3 ]
  workflow_dispatch:
  
jobs:
  run_checkstyle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Java 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    
    - name: Cache Maven Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run Checkstyle
      run: mvn checkstyle:check

    - name: report 
      if: ${{ always() }}
      uses: actions/upload-artifact@v2.2.3
      with:
        name: checkstyle-result
        path: ./target/checkstyle-result.xml
