name: Run Checkstyle

on:
  push:
  pull_request_target:
    branches: [ master ]

jobs:
  run_checkstyle:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: 'maven'

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-result
          path: ./target/checkstyle-result.xml
