# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Run Checkstyle

on:
  push:    
  
jobs:
  run_checkstyle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Java 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: 'maven'
    
    - name: Run Checkstyle
      run: mvn checkstyle:check

    - name: report 
      if: ${{ always() }}
      uses: actions/upload-artifact@v2.2.3
      with:
        name: checkstyle-result
        path: ./target/checkstyle-result.xml
