# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Create Documentation

on:
  push:
    branches: [ master, Version3 ]
  pull_request:
    branches: [ master, Version3 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: 'false'
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: register desmoj to maven 
      run: mvn install:install-file -Dfile=./libraries/DesmoJ/desmoj-2.5.1e-bin.jar -Dversion=2.5.1e -DgeneratePom=true -DgroupId=desmoj -DartifactId=desmoj -Dpackaging=jar
    
    - name: Build JavaDoc with Maven
      run:  mvn javadoc:javadoc
      
    - name: Move website to docs
      run: | 
        rm -rf ./docs && mkdir -p ./docs && cp -r ./target/site/apidocs/. ./docs/
      
    - name: push updated doc
      uses: EndBug/add-and-commit@v7
      with:
        add: './docs/'
        author_name: 'Documentation_Bot'
        message: 'Updated Documentation Beep Boop'
