# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publish Artifact

on:
  push:
    branches: [ Version3 ]
  pull_request:
    branches: [ Version3 ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: register desmoj to maven 
      run: mvn install:install-file -Dfile=./libraries/DesmoJ/desmoj-2.5.1e-bin.jar -Dversion=2.5.1e -DgeneratePom=true -DgroupId=desmoj -DartifactId=desmoj -Dpackaging=jar
    
    - name: Build with Maven
      run: |
          mvn -B package --file pom.xml
          mkdir staging
          cp target/*.jar stating
      
      
    - name: upload artifacts
      uses: actions/upload-artifacts@v2.2.3
      with:
        name: miSim 3.0
        path: ./stating/
