name: Release Http Load Generator

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: 'maven'

      - name: Configure Git
        run: |
          git config --global committer.email "noreply@github.com"
          git config --global committer.name "GitHub Release Workflow"
          git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global author.name "${GITHUB_ACTOR}"
      - name: Get Maven version
        run: |
          export MAVEN_VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed "s/-SNAPSHOT$//" )
          echo "Retreived Maven Version: $MAVEN_VERSION"
          echo "MAVEN_VERSION=$MAVEN_VERSION" >> $GITHUB_ENV
      - name: Release Maven Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B release:prepare release:perform