# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Update Documentation

on:
  push: 
    branches: [master]
  workflow_dispatch:

jobs:
  build_documentation:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Set up Java 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: 'maven'

    - name: Build JavaDoc with Maven
      run: |
       mvn -B javadoc:javadoc "-Dnotimestamp=true" "-Dcheckstyle.skipExec=true"
       mvn -B javadoc:jar  "-Dcheckstyle.skipExec=true"
      
    
    - name: Upload JavaDoc as HTML
      uses: actions/upload-artifact@v2
      with:
        name: JavaDoc
        path: ./target/site/apidocs
    
    - name: Upload JavaDoc as JAR
      uses: actions/upload-artifact@v2
      with:
        name: JavaDocJar
        path: ./target/misim-javadoc.jar
   
        
  push_documentation_to_gh-pages:
    needs: build_documentation
  
    runs-on: ubuntu-latest
  
    steps:
    - name: Download JavaDoc Artifact
      uses: actions/download-artifact@v2
      with:
        name: JavaDoc
        path: ~/docs/
   
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
   
    - name: Commit Files
      run: |
        git config --local user.email "st148345@stud.uni-stuttgart.de"
        git config --local user.name "DocumentationBot[bot]"
        git checkout gh-pages
        git pull
        cp -rpv ~/docs/. .
        
    - name: Check for changes
      run: |
        if git diff --quiet; then
          echo "changes_exist=false" >> $GITHUB_ENV
        else
          echo "changes_exist=true" >> $GITHUB_ENV
        fi
        echo "Changes exist: $changes_exist"
    
    - name: Add Files
      if: env.changes_exist == 'true'
      run: |
        git add .
        git commit -m "Updated documentation" --allow-empty
        
    - name: Push changes
      if: env.changes_exist == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
