# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Update Documentation

on:
  push: 
    branches: [master]
  workflow_dispatch:

jobs:
  update_documentation:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Set up Java 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    
    - name: Cache Maven Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build JavaDoc with Maven
      run:  mvn javadoc:javadoc "-Dnotimestamp=true" "-Dcheckstyle.skipExec=true"
      
    - name: Move Website to /docs
      run: | 
        rm -rf ./docs && mkdir -p ./docs && cp -rpv ./target/site/apidocs/. ./docs/
      
    - name: push updated doc
      uses: EndBug/add-and-commit@v7
      with:
        add: './docs/'
        author_name: Documentation_Bot
        author_email: st148345@stud.uni-stuttgart.de
        default_author: user_info
        message: '[Bot] :robot: Updated Documentation '
