# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Update Documentation

on:
  push: 
    branches: [master]
  workflow_dispatch:

jobs:
  build_documentation:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Set up Java 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: 'maven'

    - name: Build JavaDoc with Maven
      run:  mvn -B javadoc:javadoc "-Dnotimestamp=true" "-Dcheckstyle.skipExec=true"
    
    - name: test
      run: cd target/site/apidocs && ls
    
    - name: Cache Site      
      uses: actions/cache@v2
      with:
       path: .
       key: newjavadoc2
   
        
  push_documentation_to_gh-pages:
    needs: build_documentation
  
    runs-on: ubuntu-latest
  
    steps:
    - name: Load Site Cache
      uses: actions/cache@v2
      with:
       path: .
       key: newjavadoc2
    
    - name: test
      run: ls && exit
         
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
   
    - name: Commit Files
      run: |
        git config --local user.email "st148345@stud.uni-stuttgart.de"
        git config --local user.name "DocumentationBot[bot]"
        git checkout gh-pages
        git pull
        cp -rpv ~/docs/. .
        git add .
        git commit -m "Updated documentation" --allow-empty
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
